### ISSUE TITLE
Mapping the "convergence ratio"

### ISSUE THREAD

**Issue by lschmitz** [bcohn12/retina#18]
Let's assume a user has counts for both retinal ganglion cells and photoreceptors for the same retina. Let's further assume that these cell counts come from different sampling locations.

How can we implement the mapping of the convergence ratio (= photoreceptor/RGC)?

I suggest following an approach guided by the average map function (composite_map).

**Comment by briancohn** [comment]
if they're at different sampling locations then there's many approaches
one way could be to create a thin plate spline for each, then simply divide one surface by the other at each of N gridpoints, plotting the ratio across the retina

**Comment by lschmitz** [comment]
that's basically the approach from composite_map right? (well, except we need division, not the mean)
