### ISSUE TITLE
Quantifying retinal topography

### ISSUE THREAD

**Issue by lschmitz** [bcohn12/retina#19]
Users will benefit from the ability to quantify retinal landmarks. For an example, see [http://jov.arvojournals.org/article.aspx?articleid=2191987](url).

Let's start simple. Where is the location of the highest density in latitude and longitude relative to the pole?

At least two approaches are feasible. Calculate peak position on the basis of the real counts (1), or estimated from the fitted surface (2).

Approach 1 may work like this:

`findPeak <- function(my_retina){
	coord <- my_retina$trimmed_data
	peak_temp <- coord[which.max(coord$z),]
	peak <- data.frame(latitude=abs(peak_temp[,1]), longitude=peak_temp[,2], peak=peak_temp[,3])
	return(peak)
	}`

Approach 2 should work with predictSurface.

**Comment by briancohn** [comment]
how do people most often refer to the peak location?

**Comment by briancohn** [comment]
and how is it used with statistics?
Do people say that the peak longitude is significantly shifted in species A vs Species B?

**Comment by lschmitz** [comment]
Peak RGC density, usually associated with area centralis or fovea. Its position may be related to habitat/ecology, so one would test across species or across an ontogenetic series.
