### ISSUE TITLE
refactor IJ and spherical coordinate functionality

### ISSUE THREAD

**Issue by briancohn** [bcohn12/retina#21]

**Comment by bc** [comment]
- [x] spherical coordinate plot only take in dataframes instead of filepaths/folderpaths
- [x] lapply the coordinate transform to a list of pointsets instead of only allowing falc & points
- [x] move all IJ stuff outside of retina_object
- [x] remove all tricomposite work, remove unused functions

**Comment by bc** [comment]
-[ ] remove path requirements from retistruct calls
