### ISSUE TITLE
How to use non-uniformed xyz coordinates?

### ISSUE THREAD

**Issue by kevin020792** [bcohn12/retina#35]
Hello!
I used a non-uniformed sampling grid and I recorded every (x,y) coordniates in a csv file, but I don't know how to input this file into retina_object().
Is there any description or tutorial about using a non-uniformed sampling grid?
Thanks!

**Comment by lschmitz** [comment]
Hi Kevin, did @briancohn get back to you yet separately?

**Comment by kevin020792** [comment]
H! Yes, we've discussed some alternative solutions. I think this issue is closed! Thanks for all of your assistance!
