### ISSUE TITLE
devtools issue:, specifically with curl

### ISSUE THREAD

**Issue by lschmitz** [bcohn12/retina#36]
devtools::install_github('bc/retina')
Error in curl::curl_fetch_memory(url, handle = h) : 
  Failed to connect to api.github.com port 80: Timed out

**Comment by bc** [comment]
update devtools, if that doesn’t work, clone the repo via Zip file on the main page, cd into that folder using git bash on windows, or terminal on Mac. devtools::install()

**Comment by bc** [comment]
Let me know how those instructions did^^

If the port times out there’s also a chance that the internet wasn’t reliable at the time you ran the code
