### ISSUE TITLE
Trying to install retina

### ISSUE THREAD

**Issue by ades12345** [bcohn12/retina#42]
Hey Brian,
I used retina quite a bit a few years ago and need it again. I am trying to install retina and keep getting an error. I keep getting "Error: object 'Outline' is not exported by 'namespace:retistruct'"
Any thoughts? Thank you!

**Comment by bc** [comment]
I have something you can try:
[Archive.zip](https://github.com/bc/retina/files/3903152/Archive.zip)
open prep-retina and change the file paths to the locations for your retina locally. be sure to run source("helper_functions.r") first so all the functions are loaded. let me know how this goes

**Comment by bc** [comment]
I added a completely new version of Retina, download it and run `source('main.r')`while the working directory is set within the unzipped folder, then let me know if you're able to run the sample retina and get the plots successfully

download link: https://github.com/bc/retina/archive/master.zip

**Comment by bc** [comment]
Any luck?
