### ISSUE TITLE
Installing R package on OS Big Sur

### ISSUE THREAD

**Issue by VaniMoreno29** [bcohn12/retina#54]
Hi Brian, 

I am working on a MSc project that involves counting cell density and creating topographical maps of flounder retina. I currently am running R version 4.2.3 arm64 and Rstudio 2012.03.0 (most updated versions), and i am trying to install the retina package through R. I am getting the following error:

Warning in install.packages :
  package ‘retina’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

I am not very familiar with R, do i need to install other packages or downgrade the version? I thank you for your time in assisting!

Vanessa Moreno
University of North Carolina Wilmington

**Comment by lschmitz** [comment]
Hi, Vanessa! Please download directly from GitHub (click on Code => download zip) and proceed from there. The package is not on CRAN. Please keep us posted. Cheers!
