### ISSUE TITLE
Dependency retistructgui can't be installed

### ISSUE THREAD

**Issue by EPMalkemper** [bcohn12/retina#6]
I always get the following error. Could it be that the retistructgui does not exist anymore but is included in retistruct?

ERROR: dependency 'retistructgui' is not available for package 'retina'
- removing 'C:/Users/Pascal/Documents/R/win-library/3.3/retina'

**Comment by briancohn** [comment]
Hi! thanks for posting the issue. 
1. Which step of the installation process/tutorial do you get to this error? 
installation guide: https://github.com/bcohn12/retina/blob/master/install.md
tutorial: https://github.com/bcohn12/retina/blob/master/tutorial.md
2. Are you using R 3.3.1 or R 3.3.0?

**Comment by EPMalkemper** [comment]
Hi,

I am using R 3.3.1 and repeated the steps. Seems to work now - did you fix it?

I'll try with data the next days and keep you updated.

Thanks

**Comment by briancohn** [comment]
Nope I haven't changed anything! Please do let me know if you get this issue (or any other issue)! The bugs that show up inconsistently are the hardest to catch & fix but I'm up for the challenge.

**Comment by briancohn** [comment]
have you had any luck with this issue?

**Comment by EPMalkemper** [comment]
Yes ,this issue was solved but I still haven’t succeeded in using your script for my red fox data. Thanks your help, anyway.

Von: Brian Cohn [mailto:notifications@github.com]
Gesendet: 11 July 2017 20:01
An: briancohn/retina
Cc: Malkemper, Pascal, Dr.; Author
Betreff: Re: [briancohn/retina] Dependency retistructgui can't be installed (#6)


have you had any luck with this issue?
